export const alertConstants = {
  SUCCESS: "ALERT_SUCCESS",
  ERROR: "ALERT_ERROR",
  CLEAR: "ALERT_CLEAR",
};

export const userConstants = {
  REGISTER_REQUEST: "USERS_REGISTER_REQUEST",
  REGISTER_SUCCESS: "USERS_REGISTER_SUCCESS",
  REGISTER_FAILURE: "USERS_REGISTER_FAILURE",

  LOGIN_REQUEST: "USERS_LOGIN_REQUEST",
  LOGIN_SUCCESS: "USERS_LOGIN_SUCCESS",
  LOGIN_FAILURE: "USERS_LOGIN_FAILURE",
  GET_USER_DETAILS: "USERS_AUTO_LOGIN_REQUEST",
  LOGOUT: "USERS_LOGOUT",
};

export const campaignConstants = {
  LOAD_CAMPAIGNS: "LOAD_CAMPAIGNS",
  CAMPAIGNS_LOADED: "CAMPAIGNS_LOADED",
  LOAD_CAMPAIGN: "LOAD_CAMPAIGN",
};
