export const alertConstants = {
  SUCCESS: "ALERT_SUCCESS",
  ERROR: "ALERT_ERROR",
  CLEAR: "ALERT_CLEAR",
};

export const userConstants = {
  REGISTER_REQUEST: "REGISTER_REQUEST",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAILED: "REGISTER_FAILED",

  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILED: "LOGIN_FAILED",
  GET_USER_DETAILS: "GET_USER_DETAILS",
  LOGOUT: "LOGOUT",
};

export const campaignConstants = {
  CREATE_CAMPAIGN: "CREATE_CAMPAIGN",
  CREATE_CAMPAIGN_COMPLETED: "CREATE_CAMPAIGN_COMPLETED",
  CREATE_CAMPAIGN_FAILED: "CREATE_CAMPAIGN_FAILED",

  LOAD_ALL_CAMPAIGNS: "LOAD_ALL_CAMPAIGNS",
  LOAD_ALL_CAMPAIGNS_COMPLETED: "LOAD_ALL_CAMPAIGNS_COMPLETED",

  LOAD_USER_CAMPAIGNS: "LOAD_USER_CAMPAIGNS",
  LOAD_USER_CAMPAIGNS_COMPLETED: "LOAD_USER_CAMPAIGNS_COMPLETED",

  GET_CAMPAIGN_DETAILS: "GET_CAMPAIGN_DETAILS",
  GET_CAMPAIGN_DETAILS_COMPLETED: "GET_CAMPAIGN_DETAILS_COMPLETED",

  RESET_REDUCER: "RESET_REDUCER",
};

export const categoryConstants = {
  LOAD_CATEGORY: "LOAD_CATEGORY",
  CATEGORY_LOADED: "CATEGORY_LOADED",
};
